Repository smartdevicelink/sdl_java_suite, pull requests merged in 2018-08, with the labels that each got.

#834 fix IllegalStateException starting service
  sdl_android/build.gradle
  sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java
Labels: bug, high priority

#832 App Icon Resumption Revision
  sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java
  sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/RegisterAppInterfaceResponse.java
Labels: proposal

#831 Feature/issue 740 static icon names
  sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/StaticIconNameTests.java
  sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/StaticIconName.java
Labels: proposal

#836 Feature/issue 739 choice vr optional
  sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/ChoiceTests.java
  sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/Choice.java
Labels: proposal

#851 add enum predefinedlayout
  sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/enums/PredefinedLayoutTests.java
  sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/enums/PredefinedLayout.java
Labels: enhancement
